// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Branch struct {
	Id           int32   `json:"Id"`
	Name         string  `json:"Name"`
	MaxUsers     int32   `json:"MaxUsers"`
	CurrentUsers int32   `json:"CurrentUsers"`
	GroupIds     []int32 `json:"GroupIds"`
}
